// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title EcoBidBadge
 * @notice Immutable, non-transferable (Soulbound) registry for EcoBid ESG
 *         verification records.
 *
 * Each SME assessment that passes the minimum evidence threshold (medium or
 * above) produces a SHA-256 content hash of the final report.  That hash is
 * anchored here by the platform s trusted backend wallet as a permanent,
 * tamper-proof audit trail.
 *
 * Design choices
 * ──────────────
 * - Soulbound: tokens are bound to the recipient s address; transfer and
 *   approval functions are disabled (EIP-5192 pattern).
 * - One token per assessment: each unique report hash may be minted exactly
 *   once; duplicates revert.
 * - Platform-controlled minting: only the contract owner (the C-Step
 *   backend wallet) may mint, preventing third-party greenwashing.
 * - Full on-chain query surface: look up any token by its report hash, and
 *   retrieve the full metadata for any token ID.
 */
contract EcoBidBadge {

    // ─────────────────────────────────────────────────────────────────────
    // Types
    // ─────────────────────────────────────────────────────────────────────

    /// @notice The tier awarded to the SME for this assessment period.
    enum Tier { Bronze, Silver, Gold }

    /// @notice Full metadata stored on-chain for every minted badge.
    struct BadgeRecord {
        /// @dev The unique assessment ID generated by the backend (UUID).
        string  assessmentID;
        /// @dev The wallet/identifier of the SME that owns this badge.
        address recipient;
        /// @dev SHA-256 hex hash of the canonical JSON report payload.
        bytes32 reportHash;
        /// @dev CO2e footprint in grams (kg * 1000 to avoid decimals).
        uint256 co2eGrams;
        /// @dev Industry baseline CO2e in grams used for tier comparison.
        uint256 baselineGrams;
        /// @dev The tier awarded at the time of minting.
        Tier    tier;
        /// @dev Unix timestamp of when the record was anchored.
        uint256 anchoredAt;
    }

    // ─────────────────────────────────────────────────────────────────────
    // State
    // ─────────────────────────────────────────────────────────────────────

    address public owner;

    uint256 private _nextTokenID;

    /// tokenID => record
    mapping(uint256 => BadgeRecord) private _records;

    /// tokenID => soulbound holder address
    mapping(uint256 => address) private _holderOf;

    /// holder address => list of tokenIDs
    mapping(address => uint256[]) private _tokensOf;

    /// reportHash => tokenID (0 means not yet minted)
    mapping(bytes32 => uint256) private _tokenByHash;

    /// reportHash => whether a token has been minted for this hash
    mapping(bytes32 => bool) private _hashMinted;

    // ─────────────────────────────────────────────────────────────────────
    // Events
    // ─────────────────────────────────────────────────────────────────────

    event BadgeMinted(
        uint256 indexed tokenID,
        address indexed recipient,
        bytes32 indexed reportHash,
        string  assessmentID,
        Tier    tier,
        uint256 co2eGrams,
        uint256 anchoredAt
    );

    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );

    // ─────────────────────────────────────────────────────────────────────
    // Errors
    // ─────────────────────────────────────────────────────────────────────

    error Unauthorized();
    error AlreadyMinted(bytes32 reportHash);
    error TokenNotFound(uint256 tokenID);
    error HashNotFound(bytes32 reportHash);
    error Soulbound();
    error ZeroAddress();
    error EmptyAssessmentID();
    error ZeroCO2e();

    // ─────────────────────────────────────────────────────────────────────
    // Constructor
    // ─────────────────────────────────────────────────────────────────────

    constructor() {
        owner = msg.sender;
        _nextTokenID = 1; // start IDs at 1 so 0 can mean "not found"
    }

    // ─────────────────────────────────────────────────────────────────────
    // Modifiers
    // ─────────────────────────────────────────────────────────────────────

    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Admin
    // ─────────────────────────────────────────────────────────────────────

    /**
     * @notice Transfer contract ownership to a new address.
     * @param newOwner Address of the new owner (must be non-zero).
     */
    function transferOwnership(address newOwner) external onlyOwner {
        if (newOwner == address(0)) revert ZeroAddress();
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Minting
    // ─────────────────────────────────────────────────────────────────────

    /**
     * @notice Anchor a verified ESG assessment on-chain as a Soulbound badge.
     *
     * @param recipient     The SME Ethereum address that will hold the badge.
     * @param reportHash    SHA-256 hash (bytes32) of the canonical JSON report.
     * @param assessmentID  Backend UUID of the assessment.
     * @param co2eGrams     Total CO2e footprint in grams (kg x 1000).
     * @param baselineGrams Industry baseline CO2e in grams.
     * @param tier          Tier awarded: 0=Bronze, 1=Silver, 2=Gold.
     * @return tokenID      The newly minted token ID.
     */
    function mint(
        address recipient,
        bytes32 reportHash,
        string  calldata assessmentID,
        uint256 co2eGrams,
        uint256 baselineGrams,
        Tier    tier
    )
        external
        onlyOwner
        returns (uint256 tokenID)
    {
        if (recipient    == address(0))      revert ZeroAddress();
        if (_hashMinted[reportHash])         revert AlreadyMinted(reportHash);
        if (bytes(assessmentID).length == 0) revert EmptyAssessmentID();
        if (co2eGrams == 0)                  revert ZeroCO2e();

        tokenID = _nextTokenID++;

        _records[tokenID] = BadgeRecord({
            assessmentID:  assessmentID,
            recipient:     recipient,
            reportHash:    reportHash,
            co2eGrams:     co2eGrams,
            baselineGrams: baselineGrams,
            tier:          tier,
            anchoredAt:    block.timestamp
        });

        _holderOf[tokenID]        = recipient;
        _tokensOf[recipient].push(tokenID);
        _tokenByHash[reportHash]  = tokenID;
        _hashMinted[reportHash]   = true;

        emit BadgeMinted(
            tokenID,
            recipient,
            reportHash,
            assessmentID,
            tier,
            co2eGrams,
            block.timestamp
        );
    }

    // ─────────────────────────────────────────────────────────────────────
    // Queries
    // ─────────────────────────────────────────────────────────────────────

    /**
     * @notice Look up the full badge record for a given token ID.
     */
    function getRecord(uint256 tokenID)
        external
        view
        returns (BadgeRecord memory)
    {
        if (_holderOf[tokenID] == address(0)) revert TokenNotFound(tokenID);
        return _records[tokenID];
    }

    /**
     * @notice Look up a badge record by its report hash.
     */
    function getRecordByHash(bytes32 reportHash)
        external
        view
        returns (BadgeRecord memory)
    {
        if (!_hashMinted[reportHash]) revert HashNotFound(reportHash);
        return _records[_tokenByHash[reportHash]];
    }

    /**
     * @notice Return the token ID associated with a report hash, or 0 if
     *         it has not been minted yet.
     */
    function tokenIDForHash(bytes32 reportHash)
        external
        view
        returns (uint256)
    {
        return _hashMinted[reportHash] ? _tokenByHash[reportHash] : 0;
    }

    /**
     * @notice Check whether a report hash has already been anchored.
     */
    function isAnchored(bytes32 reportHash)
        external
        view
        returns (bool)
    {
        return _hashMinted[reportHash];
    }

    /**
     * @notice Return all token IDs held by an address.
     */
    function tokensOf(address holder)
        external
        view
        returns (uint256[] memory)
    {
        return _tokensOf[holder];
    }

    /**
     * @notice Total number of badges minted so far.
     */
    function totalSupply() external view returns (uint256) {
        return _nextTokenID - 1;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Soulbound: block all transfers
    // ─────────────────────────────────────────────────────────────────────

    /**
     * @notice Badges are non-transferable; any attempt to transfer reverts.
     */
    function transfer(address, uint256) external pure {
        revert Soulbound();
    }

    /**
     * @notice Badges are non-transferable; any attempt to approve reverts.
     */
    function approve(address, uint256) external pure {
        revert Soulbound();
    }
}
